---
name: "Implicit Step Dependencies"
emoji: ":buildkite:"
steps:
  - label: ":buildkite: Generate and upload pipeline steps"
    command: ".buildkite/upload-pipeline-steps.sh"
    depends_on: "~" # Force builds to use DAG mode
